#
# Copyright (c) 2012, Twitter, Inc. All rights reserved.
#
# Locate Breakpad client library for Linux.
#

SET(_BREAKPAD_ROOT $ENV{BREAKPAD_ROOT} ${BREAKPAD_ROOT})
LIST(APPEND _BREAKPAD_ROOT_HINTS $ENV{BREAKPAD_ROOT}/src/ ${BREAKPAD_ROOT}/src/)

FIND_PATH(BREAKPAD_INCLUDE_DIR client/linux/handler/exception_handler.h
  HINTS ${_BREAKPAD_ROOT_HINTS})
MARK_AS_ADVANCED(BREAKPAD_INCLUDE_DIR)

FIND_LIBRARY(BREAKPAD_CLIENT_LIBRARY NAMES breakpad_client
  HINTS ${_BREAKPAD_ROOT_HINTS} PATH_SUFFIXES client/linux/)
MARK_AS_ADVANCED(BREAKPAD_CLIENT_LIBRARY)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Breakpad DEFAULT_MSG
  BREAKPAD_CLIENT_LIBRARY BREAKPAD_INCLUDE_DIR)

IF(BREAKPAD_FOUND)
  SET(HAVE_BREAKPAD 1)
  SET(BREAKPAD_INCLUDE_DIRS ${BREAKPAD_INCLUDE_DIR})
  SET(BREAKPAD_LIBRARIES ${BREAKPAD_CLIENT_LIBRARY})
ENDIF()

